ktor:
    application:
        modules:
            - com.ustadmobile.testservercontroller.ApplicationKt.module
    deployment:
        port: 8080

testservercontroller:
    basedir: "./test-server-base"
    cmd: "/home/mike/AndroidStudioProjects/Respect-review/respect-test-end-to-end/android-maestro/run-server.sh"
    shutdown:
      url: "/shutdown"
